---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian9
    image: debian:9
    dockerfile: ../resources/Dockerfile.j2
  - name: debian10
    image: debian:10
    dockerfile: ../resources/Dockerfile.j2
  - name: Ubuntu16
    image: ubuntu:16.04
    dockerfile: ../resources/Dockerfile.j2
  - name: Ubuntu18
    image: ubuntu:18.04
    dockerfile: ../resources/Dockerfile.j2
  - name: CentOS7
    image: centos:7
    dockerfile: ../resources/Dockerfile.j2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  env:
    HETZNER_ROBOT_BASE_URL: http://hetzner-robot:3000
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
