---
- name: Prepare
  hosts: all
  vars:
    hetzner_installimage_robot_api_base_url: http://hetzner-robot:3000
  tasks:
    - name: Include default prepare tasks
      import_tasks: ../resources/tasks/prepare-default.yml
    - name: Create key
      uri:
        url: "{{ hetzner_installimage_robot_api_base_url }}/key"
        method: POST
        user: "robot"
        password: "secret"
        status_code: 201
        body:
          name: Existing Key
          data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSkT3A1j89RT/540ghIMHXIVwNlAEM3WtmqVG7YN/wYwtsJ8iCszg4/lXQsfLFx
          YmEVe8L9atgtMGCi5QdYPl4X/c+5YxFfm88Yjfx+2xEgUdOr864eaI22yaNMQ0AlyilmK+PcSyxKP4dzkf6B5Nsw8lhfB5n9F5md6GHLLjOG
          uBbHYlesKJKnt2cMzzS90BdRk73qW6wJ+MCUWo+cyBFZVGOzrjJGEcHewOCbVs+IJWBFSi6w1enbKGc+RY9KrnzeDKWWqzYnNofiHGVFAuMx
          rmZOasqlTIKiC2UK3RmLxZicWiQmPnpnjJRo7pL0oYM9r/sIWzD6i2S9szDy6aZ"
          fingerprint: fi:ng:er:pr:in:t0:00:00:00:00:00:00:00:00:00:00
        force_basic_auth: yes
        body_format: json
      delegate_to: localhost
      run_once: yes

- name: Prepare controller
  hosts: localhost
  tasks:
    - name: Prepare controller
      import_tasks: ../resources/tasks/prepare-controller.yml
