---
- name: Prepare
  hosts: all
  vars:
    hetzner_installimage_robot_api_base_url: http://hetzner-robot:3000
  tasks:
    - name: Include default prepare tasks
      include: ../resources/tasks/prepare-default.yml
    - name: Create base image directory for old images
      raw: "mkdir -p /root/.oldroot/nfs/images.old"
    - name: Create image file in folder for old images 
      raw: "touch /root/.oldroot/nfs/images.old/Debian-102-buster-64-minimal.tar.gz"

- name: Prepare controller
  hosts: localhost
  tasks:
    - name: Prepare controller
      include: ../resources/tasks/prepare-controller.yml