---
- name: Prepare
  hosts: all
  vars:
    hetzner_installimage_robot_api_base_url: http://hetzner-robot:3000
  tasks:
    - name: Include default prepare tasks
      include: ../resources/tasks/prepare-default.yml

- name: Prepare controller
  hosts: localhost
  tasks:
    - name: Prepare controller
      include: ../resources/tasks/prepare-controller.yml