---
- name: Prepare
  hosts: all
  tasks:
    - name: Add fake hetzner_installimage_provisioned.flag file
      raw: echo 'test' > /etc/hetzner_installimage_provisioned.flag

- name: Prepare controller
  hosts: localhost
  tasks:
    - name: Prepare controller
      import_tasks: ../resources/tasks/prepare-controller.yml
